import Head from 'next/head'
import DropControl from '../src/DropControl'

const Home = () => (
  <>
    <Head>
      <title>pudding</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <main>
      <DropControl />
    </main>
  </>
)

export default Home
